-- APPOINTMENT : APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_CNCL_YN, APNT_CNCL_YMD

SELECT 
  MCDP_CD AS `진료과 코드`, 
  COUNT(DISTINCT PT_NO) AS `5월예약건수`
FROM 
  APPOINTMENT
WHERE 
  APNT_YMD >= '2022-05-01 00:00:00'
  AND APNT_YMD < '2022-06-01 00:00:00'
GROUP BY 
  MCDP_CD
ORDER BY 
  `5월예약건수` ASC,
  MCDP_CD ASC;